# Generated by Django 5.1.4 on 2025-06-18 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gimnasioApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membresiaasignada',
            name='dateFinal',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='membresiaasignada',
            name='miembro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='miembro', to='gimnasioApp.usuariogym'),
        ),
    ]
