# Generated by Django 5.1.4 on 2026-07-14 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gimnasioApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='membresia',
            name='max_multiplier',
            field=models.PositiveIntegerField(default=1, help_text='Máximo multiplicador permitido (1 = no multiplicable)'),
        ),
        migrations.AddField(
            model_name='membresiaasignada',
            name='multiplier',
            field=models.PositiveIntegerField(default=1, help_text='Multiplicador de duración/precio (1 = sin multiplicar)'),
        ),
        migrations.AlterField(
            model_name='membresia',
            name='duration',
            field=models.PositiveIntegerField(help_text='Duración en días (1-365)'),
        ),
        migrations.AlterField(
            model_name='membresia',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='membresia',
            unique_together={('gimnasio', 'name')},
        ),
    ]
