# Generated by Django 5.1.4 on 2025-01-26 07:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gimnasioApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membresia',
            name='name',
            field=models.CharField(choices=[('básico', 'Básico'), ('premium', 'Premium'), ('VIP', 'VIP')], default='basico', max_length=10),
        ),
        migrations.CreateModel(
            name='MembresiaAsignada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateInitial', models.DateField(max_length=200)),
                ('dateFinal', models.DateField(blank=True, max_length=200, null=True)),
                ('membresia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gimnasioApp.membresia')),
                ('miembro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membresias', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
