# Generated by Django 5.1.4 on 2025-06-24 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gimnasioApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='membresia',
            options={'verbose_name': 'Membresia', 'verbose_name_plural': 'Membresias'},
        ),
        migrations.RemoveField(
            model_name='membresia',
            name='created_at',
        ),
    ]
