# Generated by Django 5.1.4 on 2026-07-13 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gimnasioApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='membresiaasignada',
            name='discount_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='membresiaasignada',
            name='multiplier',
            field=models.DecimalField(decimal_places=1, default=1, max_digits=4),
        ),
        migrations.CreateModel(
            name='PagoMembresia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_pago', models.DateTimeField(auto_now_add=True)),
                ('metodo_pago', models.CharField(choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia'), ('nequi', 'Nequi')], max_length=20)),
                ('nota', models.TextField(blank=True, default='')),
                ('membresia_asignada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='gimnasioApp.membresiaasignada')),
            ],
            options={
                'verbose_name': 'Pago Membresia',
                'verbose_name_plural': 'Pagos Membresia',
                'db_table': 'pago_membresia',
                'ordering': ['-fecha_pago'],
            },
        ),
    ]
