# Generated by Django 5.1.4 on 2025-01-11 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gimnasioApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrarusuario',
            name='img',
            field=models.ImageField(blank=True, default='', null=True, upload_to='fotos/'),
        ),
    ]
