# Generated by Django 5.1.4 on 2025-01-12 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gimnasioApp', '0002_registrarusuario_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registrarusuario',
            old_name='img',
            new_name='avatar',
        ),
    ]
