# Generated by Django 5.1.4 on 2025-06-25 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gimnasioApp', '0002_alter_membresia_options_remove_membresia_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuariogym',
            options={'ordering': ['-created_at'], 'verbose_name': 'UsuarioGym', 'verbose_name_plural': 'UsuarioGyms'},
        ),
        migrations.AlterModelOptions(
            name='usuariogymday',
            options={'ordering': ['-created_at'], 'verbose_name': 'UsuarioGymDay', 'verbose_name_plural': 'UsuarioGymDays'},
        ),
    ]
