# Generated by Django 5.1.4 on 2024-12-19 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gimnasioApp', '0002_registrarusuario_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registrarusuario',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.RemoveField(
            model_name='registrarusuario',
            name='user',
        ),
        migrations.AddField(
            model_name='registrarusuario',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='registrarusuario',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AlterField(
            model_name='registrarusuario',
            name='lastname',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='registrarusuario',
            name='name',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='registrarusuario',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
        migrations.AlterField(
            model_name='registrarusuario',
            name='roles',
            field=models.CharField(choices=[('recepcion', 'Recepcionista'), ('admin', 'Administrador')], default='recepcion', max_length=10),
        ),
        migrations.AlterModelTable(
            name='registrarusuario',
            table='user',
        ),
    ]
