# Generated by Django 5.1.4 on 2025-01-26 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gimnasioApp', '0002_alter_membresia_name_membresiaasignada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membresiaasignada',
            name='miembro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membresias', to='gimnasioApp.usuariogym'),
        ),
    ]
