# Generated by Django 5.1.4 on 2025-01-21 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gimnasioApp', '0003_rename_img_registrarusuario_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrarMembresias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('duration', models.CharField(max_length=100)),
                ('state', models.BooleanField()),
            ],
            options={
                'verbose_name': 'RegistrarMembresia',
                'verbose_name_plural': 'RegistrarMembresias',
                'db_table': 'RegistrarMembresia',
            },
        ),
    ]
