# Generated by Django 5.1.4 on 2026-04-02 01:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gimnasioApp', '0003_alter_usuariogym_options_alter_usuariogymday_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gimnasio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(blank=True, default='', max_length=200)),
                ('phone', models.CharField(blank=True, default='', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Gimnasio',
                'verbose_name_plural': 'Gimnasios',
                'db_table': 'gimnasio',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='membresia',
            name='gimnasio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='membresias', to='gimnasioApp.gimnasio'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='gimnasio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to='gimnasioApp.gimnasio'),
        ),
        migrations.AddField(
            model_name='usuariogym',
            name='gimnasio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='miembros', to='gimnasioApp.gimnasio'),
        ),
        migrations.AddField(
            model_name='usuariogymday',
            name='gimnasio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='miembros_diarios', to='gimnasioApp.gimnasio'),
        ),
    ]
