# Generated by Django 5.1.4 on 2025-01-27 06:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gimnasioApp', '0003_alter_membresiaasignada_miembro'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='membresiaasignada',
            options={'verbose_name': 'MembresiaAsignada', 'verbose_name_plural': 'MembresiaAsignadas'},
        ),
        migrations.AlterField(
            model_name='membresiaasignada',
            name='miembro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='miembros', to='gimnasioApp.usuariogym'),
        ),
        migrations.AlterModelTable(
            name='membresiaasignada',
            table='membresiaAsignada',
        ),
    ]
