# Generated by Django 5.1.4 on 2025-01-22 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gimnasioApp', '0004_registrarmembresias'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrarmembresias',
            name='state',
        ),
        migrations.AddField(
            model_name='registrarmembresias',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='registrarmembresias',
            name='duration',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterModelTable(
            name='registrarmembresias',
            table='membresia',
        ),
    ]
