# Generated by Django 5.1.4 on 2026-07-15 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gimnasioApp', '0002_membresiaasignada_discount_percent_and_more'),
        ('gimnasioApp', '0004_alter_membresia_name_unique_together'),
    ]

    operations = [
    ]
