# Generated by Django 5.1.4 on 2026-04-23 07:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gimnasioApp', '0004_gimnasio_membresia_gimnasio_usuario_gimnasio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='membresiaasignada',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
