# Generated by Django 5.1.4 on 2026-04-26 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gimnasioApp', '0005_membresiaasignada_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='membresiaasignada',
            name='notified_at',
            field=models.DateTimeField(blank=True, help_text='Fecha en que se marcó como notificada/leída', null=True),
        ),
    ]
