# Generated by Django 5.1.4 on 2026-07-15 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gimnasioApp', '0005_merge_20260715_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membresiaasignada',
            name='discount_percent',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Descuento porcentual (0-100)', max_digits=5),
        ),
        migrations.AlterField(
            model_name='membresiaasignada',
            name='multiplier',
            field=models.DecimalField(decimal_places=1, default=1, help_text='Multiplicador de duración/precio (1 = sin multiplicar)', max_digits=4),
        ),
    ]
