# Generated by Django 5.1.4 on 2025-01-22 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gimnasioApp', '0005_remove_registrarmembresias_state_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrarmembresias',
            name='name',
            field=models.CharField(choices=[('basico', 'Básico'), ('premium', 'Premium'), ('VIP', 'VIP')], default='basico', max_length=10),
        ),
    ]
