# Generated by Django 5.1.4 on 2026-04-28 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gimnasioApp', '0006_membresiaasignada_notified_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='membresiaasignada',
            name='gimnasio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='membresias_asignadas', to='gimnasioApp.gimnasio'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='membresia',
            name='gimnasio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='membresias', to='gimnasioApp.gimnasio'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usuario',
            name='gimnasio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to='gimnasioApp.gimnasio'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usuariogym',
            name='gimnasio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='miembros', to='gimnasioApp.gimnasio'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usuariogymday',
            name='gimnasio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='miembros_diarios', to='gimnasioApp.gimnasio'),
            preserve_default=False,
        ),
    ]
